
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 26 13:46:59 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 37;
  public static final int LBRACKET = 7;
  public static final int CONST = 6;
  public static final int NUMCONST = 18;
  public static final int LPAREN = 9;
  public static final int SEMI = 5;
  public static final int CONTINUE = 26;
  public static final int DECR = 29;
  public static final int INCR = 28;
  public static final int FOR = 42;
  public static final int MINUS = 14;
  public static final int RPAREN = 10;
  public static final int AND = 31;
  public static final int LT = 35;
  public static final int OR = 30;
  public static final int COMMA = 15;
  public static final int DIV = 39;
  public static final int PLUS = 13;
  public static final int ASSIGN = 24;
  public static final int IF = 22;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int RBRACKET = 8;
  public static final int EQUAL = 11;
  public static final int NEW = 32;
  public static final int error = 1;
  public static final int MUL = 38;
  public static final int MOD = 40;
  public static final int BREAK = 25;
  public static final int IDENT = 21;
  public static final int VOID = 17;
  public static final int GTE = 36;
  public static final int LBRACE = 3;
  public static final int ELSE = 23;
  public static final int READ = 27;
  public static final int CHARCONST = 19;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 20;
  public static final int PROG = 2;
  public static final int DIFF = 33;
  public static final int GT = 34;
  public static final int PRINT = 16;
}

